(cl:defpackage referee-srv
  (:use )
  (:export
   "SENDDIMENSIONS"
   "<SENDDIMENSIONS-REQUEST>"
   "SENDDIMENSIONS-REQUEST"
   "<SENDDIMENSIONS-RESPONSE>"
   "SENDDIMENSIONS-RESPONSE"
   "TEAMREADY"
   "<TEAMREADY-REQUEST>"
   "TEAMREADY-REQUEST"
   "<TEAMREADY-RESPONSE>"
   "TEAMREADY-RESPONSE"
   "SENDCOLOR"
   "<SENDCOLOR-REQUEST>"
   "SENDCOLOR-REQUEST"
   "<SENDCOLOR-RESPONSE>"
   "SENDCOLOR-RESPONSE"
  ))

