// Generated by gencpp from file referee/SendColorRequest.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_SENDCOLORREQUEST_H
#define REFEREE_MESSAGE_SENDCOLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace referee
{
template <class ContainerAllocator>
struct SendColorRequest_
{
  typedef SendColorRequest_<ContainerAllocator> Type;

  SendColorRequest_()
    : team()
    , color()  {
    }
  SendColorRequest_(const ContainerAllocator& _alloc)
    : team(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_type;
  _team_type team;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::referee::SendColorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::referee::SendColorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendColorRequest_

typedef ::referee::SendColorRequest_<std::allocator<void> > SendColorRequest;

typedef boost::shared_ptr< ::referee::SendColorRequest > SendColorRequestPtr;
typedef boost::shared_ptr< ::referee::SendColorRequest const> SendColorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::referee::SendColorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::referee::SendColorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace referee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendColorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendColorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendColorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendColorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::referee::SendColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7aefec83096b40e30fea73e2ede95838";
  }

  static const char* value(const ::referee::SendColorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7aefec83096b40e3ULL;
  static const uint64_t static_value2 = 0x0fea73e2ede95838ULL;
};

template<class ContainerAllocator>
struct DataType< ::referee::SendColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "referee/SendColorRequest";
  }

  static const char* value(const ::referee::SendColorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::referee::SendColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string team\n\
string color\n\
";
  }

  static const char* value(const ::referee::SendColorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::referee::SendColorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.team);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendColorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::referee::SendColorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::referee::SendColorRequest_<ContainerAllocator>& v)
  {
    s << indent << "team: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFEREE_MESSAGE_SENDCOLORREQUEST_H
