// Generated by gencpp from file referee/SendColorResponse.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_SENDCOLORRESPONSE_H
#define REFEREE_MESSAGE_SENDCOLORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace referee
{
template <class ContainerAllocator>
struct SendColorResponse_
{
  typedef SendColorResponse_<ContainerAllocator> Type;

  SendColorResponse_()
    : ok(false)
    , correctColor()  {
    }
  SendColorResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , correctColor(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _correctColor_type;
  _correctColor_type correctColor;




  typedef boost::shared_ptr< ::referee::SendColorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::referee::SendColorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendColorResponse_

typedef ::referee::SendColorResponse_<std::allocator<void> > SendColorResponse;

typedef boost::shared_ptr< ::referee::SendColorResponse > SendColorResponsePtr;
typedef boost::shared_ptr< ::referee::SendColorResponse const> SendColorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::referee::SendColorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::referee::SendColorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace referee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendColorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendColorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendColorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendColorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendColorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendColorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::referee::SendColorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4152949fd47712cb5bc612ded647192a";
  }

  static const char* value(const ::referee::SendColorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4152949fd47712cbULL;
  static const uint64_t static_value2 = 0x5bc612ded647192aULL;
};

template<class ContainerAllocator>
struct DataType< ::referee::SendColorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "referee/SendColorResponse";
  }

  static const char* value(const ::referee::SendColorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::referee::SendColorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n\
string correctColor\n\
\n\
";
  }

  static const char* value(const ::referee::SendColorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::referee::SendColorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.correctColor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendColorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::referee::SendColorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::referee::SendColorResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "correctColor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.correctColor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFEREE_MESSAGE_SENDCOLORRESPONSE_H
