// Generated by gencpp from file referee/SendDimensions.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_SENDDIMENSIONS_H
#define REFEREE_MESSAGE_SENDDIMENSIONS_H

#include <ros/service_traits.h>


#include <referee/SendDimensionsRequest.h>
#include <referee/SendDimensionsResponse.h>


namespace referee
{

struct SendDimensions
{

typedef SendDimensionsRequest Request;
typedef SendDimensionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDimensions
} // namespace referee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::referee::SendDimensions > {
  static const char* value()
  {
    return "93d19cf8b6cc6f6fec2d0c3699a876a4";
  }

  static const char* value(const ::referee::SendDimensions&) { return value(); }
};

template<>
struct DataType< ::referee::SendDimensions > {
  static const char* value()
  {
    return "referee/SendDimensions";
  }

  static const char* value(const ::referee::SendDimensions&) { return value(); }
};


// service_traits::MD5Sum< ::referee::SendDimensionsRequest> should match 
// service_traits::MD5Sum< ::referee::SendDimensions > 
template<>
struct MD5Sum< ::referee::SendDimensionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::referee::SendDimensions >::value();
  }
  static const char* value(const ::referee::SendDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::SendDimensionsRequest> should match 
// service_traits::DataType< ::referee::SendDimensions > 
template<>
struct DataType< ::referee::SendDimensionsRequest>
{
  static const char* value()
  {
    return DataType< ::referee::SendDimensions >::value();
  }
  static const char* value(const ::referee::SendDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::referee::SendDimensionsResponse> should match 
// service_traits::MD5Sum< ::referee::SendDimensions > 
template<>
struct MD5Sum< ::referee::SendDimensionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::referee::SendDimensions >::value();
  }
  static const char* value(const ::referee::SendDimensionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::SendDimensionsResponse> should match 
// service_traits::DataType< ::referee::SendDimensions > 
template<>
struct DataType< ::referee::SendDimensionsResponse>
{
  static const char* value()
  {
    return DataType< ::referee::SendDimensions >::value();
  }
  static const char* value(const ::referee::SendDimensionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFEREE_MESSAGE_SENDDIMENSIONS_H
