// Generated by gencpp from file referee/SendDimensionsRequest.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_SENDDIMENSIONSREQUEST_H
#define REFEREE_MESSAGE_SENDDIMENSIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace referee
{
template <class ContainerAllocator>
struct SendDimensionsRequest_
{
  typedef SendDimensionsRequest_<ContainerAllocator> Type;

  SendDimensionsRequest_()
    : team()
    , dimensions()  {
    }
  SendDimensionsRequest_(const ContainerAllocator& _alloc)
    : team(_alloc)
    , dimensions(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_type;
  _team_type team;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _dimensions_type;
  _dimensions_type dimensions;




  typedef boost::shared_ptr< ::referee::SendDimensionsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::referee::SendDimensionsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendDimensionsRequest_

typedef ::referee::SendDimensionsRequest_<std::allocator<void> > SendDimensionsRequest;

typedef boost::shared_ptr< ::referee::SendDimensionsRequest > SendDimensionsRequestPtr;
typedef boost::shared_ptr< ::referee::SendDimensionsRequest const> SendDimensionsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::referee::SendDimensionsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::referee::SendDimensionsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace referee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendDimensionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::referee::SendDimensionsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendDimensionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::SendDimensionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendDimensionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::SendDimensionsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::referee::SendDimensionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff271b3dbd6053796c15bfe2bbca8bdd";
  }

  static const char* value(const ::referee::SendDimensionsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff271b3dbd605379ULL;
  static const uint64_t static_value2 = 0x6c15bfe2bbca8bddULL;
};

template<class ContainerAllocator>
struct DataType< ::referee::SendDimensionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "referee/SendDimensionsRequest";
  }

  static const char* value(const ::referee::SendDimensionsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::referee::SendDimensionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string team\n\
geometry_msgs/Point dimensions\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::referee::SendDimensionsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::referee::SendDimensionsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.team);
      stream.next(m.dimensions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendDimensionsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::referee::SendDimensionsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::referee::SendDimensionsRequest_<ContainerAllocator>& v)
  {
    s << indent << "team: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team);
    s << indent << "dimensions: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.dimensions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFEREE_MESSAGE_SENDDIMENSIONSREQUEST_H
