// Generated by gencpp from file referee/SendColor.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_SENDCOLOR_H
#define REFEREE_MESSAGE_SENDCOLOR_H

#include <ros/service_traits.h>


#include <referee/SendColorRequest.h>
#include <referee/SendColorResponse.h>


namespace referee
{

struct SendColor
{

typedef SendColorRequest Request;
typedef SendColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendColor
} // namespace referee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::referee::SendColor > {
  static const char* value()
  {
    return "e6d5aa3a575bd2c74ae1fa54aa259b0b";
  }

  static const char* value(const ::referee::SendColor&) { return value(); }
};

template<>
struct DataType< ::referee::SendColor > {
  static const char* value()
  {
    return "referee/SendColor";
  }

  static const char* value(const ::referee::SendColor&) { return value(); }
};


// service_traits::MD5Sum< ::referee::SendColorRequest> should match 
// service_traits::MD5Sum< ::referee::SendColor > 
template<>
struct MD5Sum< ::referee::SendColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::referee::SendColor >::value();
  }
  static const char* value(const ::referee::SendColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::SendColorRequest> should match 
// service_traits::DataType< ::referee::SendColor > 
template<>
struct DataType< ::referee::SendColorRequest>
{
  static const char* value()
  {
    return DataType< ::referee::SendColor >::value();
  }
  static const char* value(const ::referee::SendColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::referee::SendColorResponse> should match 
// service_traits::MD5Sum< ::referee::SendColor > 
template<>
struct MD5Sum< ::referee::SendColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::referee::SendColor >::value();
  }
  static const char* value(const ::referee::SendColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::SendColorResponse> should match 
// service_traits::DataType< ::referee::SendColor > 
template<>
struct DataType< ::referee::SendColorResponse>
{
  static const char* value()
  {
    return DataType< ::referee::SendColor >::value();
  }
  static const char* value(const ::referee::SendColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFEREE_MESSAGE_SENDCOLOR_H
