// Generated by gencpp from file referee/TeamReadyRequest.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_TEAMREADYREQUEST_H
#define REFEREE_MESSAGE_TEAMREADYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace referee
{
template <class ContainerAllocator>
struct TeamReadyRequest_
{
  typedef TeamReadyRequest_<ContainerAllocator> Type;

  TeamReadyRequest_()
    : team()  {
    }
  TeamReadyRequest_(const ContainerAllocator& _alloc)
    : team(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _team_type;
  _team_type team;




  typedef boost::shared_ptr< ::referee::TeamReadyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::referee::TeamReadyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TeamReadyRequest_

typedef ::referee::TeamReadyRequest_<std::allocator<void> > TeamReadyRequest;

typedef boost::shared_ptr< ::referee::TeamReadyRequest > TeamReadyRequestPtr;
typedef boost::shared_ptr< ::referee::TeamReadyRequest const> TeamReadyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::referee::TeamReadyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::referee::TeamReadyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace referee

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::referee::TeamReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::referee::TeamReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::TeamReadyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::referee::TeamReadyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::TeamReadyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::referee::TeamReadyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::referee::TeamReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ea91258faa2e43cced50cc90a49ffff";
  }

  static const char* value(const ::referee::TeamReadyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ea91258faa2e43cULL;
  static const uint64_t static_value2 = 0xced50cc90a49ffffULL;
};

template<class ContainerAllocator>
struct DataType< ::referee::TeamReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "referee/TeamReadyRequest";
  }

  static const char* value(const ::referee::TeamReadyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::referee::TeamReadyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string team\n\
";
  }

  static const char* value(const ::referee::TeamReadyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::referee::TeamReadyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.team);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeamReadyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::referee::TeamReadyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::referee::TeamReadyRequest_<ContainerAllocator>& v)
  {
    s << indent << "team: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.team);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFEREE_MESSAGE_TEAMREADYREQUEST_H
