// Generated by gencpp from file referee/TeamReady.msg
// DO NOT EDIT!


#ifndef REFEREE_MESSAGE_TEAMREADY_H
#define REFEREE_MESSAGE_TEAMREADY_H

#include <ros/service_traits.h>


#include <referee/TeamReadyRequest.h>
#include <referee/TeamReadyResponse.h>


namespace referee
{

struct TeamReady
{

typedef TeamReadyRequest Request;
typedef TeamReadyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeamReady
} // namespace referee


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::referee::TeamReady > {
  static const char* value()
  {
    return "dde678767d5425233d0d82d47446a552";
  }

  static const char* value(const ::referee::TeamReady&) { return value(); }
};

template<>
struct DataType< ::referee::TeamReady > {
  static const char* value()
  {
    return "referee/TeamReady";
  }

  static const char* value(const ::referee::TeamReady&) { return value(); }
};


// service_traits::MD5Sum< ::referee::TeamReadyRequest> should match 
// service_traits::MD5Sum< ::referee::TeamReady > 
template<>
struct MD5Sum< ::referee::TeamReadyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::referee::TeamReady >::value();
  }
  static const char* value(const ::referee::TeamReadyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::TeamReadyRequest> should match 
// service_traits::DataType< ::referee::TeamReady > 
template<>
struct DataType< ::referee::TeamReadyRequest>
{
  static const char* value()
  {
    return DataType< ::referee::TeamReady >::value();
  }
  static const char* value(const ::referee::TeamReadyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::referee::TeamReadyResponse> should match 
// service_traits::MD5Sum< ::referee::TeamReady > 
template<>
struct MD5Sum< ::referee::TeamReadyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::referee::TeamReady >::value();
  }
  static const char* value(const ::referee::TeamReadyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::referee::TeamReadyResponse> should match 
// service_traits::DataType< ::referee::TeamReady > 
template<>
struct DataType< ::referee::TeamReadyResponse>
{
  static const char* value()
  {
    return DataType< ::referee::TeamReady >::value();
  }
  static const char* value(const ::referee::TeamReadyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFEREE_MESSAGE_TEAMREADY_H
